# Generated by Django 2.0.7 on 2019-04-11 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competencia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complograda',
            old_name='IDComp',
            new_name='competencia',
        ),
        migrations.RenameField(
            model_name='complograda',
            old_name='DNI',
            new_name='mentor',
        ),
        migrations.RenameField(
            model_name='compplanif',
            old_name='IDComp',
            new_name='competencia',
        ),
        migrations.RenameField(
            model_name='compplanif',
            old_name='IDSes',
            new_name='mentoria',
        ),
        migrations.RenameField(
            model_name='referente',
            old_name='IDComp',
            new_name='competencia',
        ),
        migrations.RenameField(
            model_name='referente',
            old_name='DNI',
            new_name='mentor',
        ),
    ]
