# Generated by Django 2.0.7 on 2019-04-25 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0013_mentor_entidad'),
        ('entidad', '0004_auto_20190425_0402'),
        ('competencia', '0003_auto_20190412_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia_Referente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('competencia', models.ForeignKey(on_delete=True, related_name='compRef', to='competencia.Competencia')),
            ],
            options={
                'verbose_name': 'Competencia de un perfil',
                'verbose_name_plural': 'Competencias de un perfil',
            },
        ),
        migrations.CreateModel(
            name='Hoja_Vida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('grado', models.CharField(blank=True, max_length=30, null=True, verbose_name='Grado')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('areasInteres', models.CharField(blank=True, max_length=200, null=True, verbose_name='areas de interes')),
                ('especialidad', models.CharField(blank=True, max_length=30, null=True, verbose_name='Especialidad')),
                ('puesto', models.CharField(blank=True, max_length=30, null=True, verbose_name='Puesto')),
                ('periodo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Periodo')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hojaVida', to='entidad.Entidad')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hojaVida', to='mentor.Mentor')),
            ],
            options={
                'verbose_name': 'Hoja de vida',
                'verbose_name_plural': 'Hojas de vida',
            },
        ),
        migrations.RemoveField(
            model_name='complograda',
            name='competencia',
        ),
        migrations.RemoveField(
            model_name='complograda',
            name='entidad',
        ),
        migrations.RemoveField(
            model_name='complograda',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='referente',
            name='competencia',
        ),
        migrations.RemoveField(
            model_name='referente',
            name='mentor',
        ),
        migrations.AddField(
            model_name='referente',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='referente',
            name='puntaje',
            field=models.FloatField(blank=True, null=True, verbose_name='Puntaje'),
        ),
        migrations.DeleteModel(
            name='CompLograda',
        ),
        migrations.AddField(
            model_name='competencia_referente',
            name='referente',
            field=models.ForeignKey(on_delete=True, related_name='compRef', to='competencia.Referente'),
        ),
        migrations.AddField(
            model_name='competencia',
            name='hojaVida',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, related_name='competencias', to='competencia.Hoja_Vida'),
        ),
    ]
