# Generated by Django 2.0.7 on 2019-04-25 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competencia', '0004_auto_20190425_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoja_vida',
            name='mentor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hojaVida', to='mentor.Mentor'),
        ),
    ]
