# Generated by Django 2.0.7 on 2019-04-11 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_auto_20190411_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Mentor', to='mentor.Mentor'),
        ),
    ]
