# Generated by Django 2.0.7 on 2019-04-12 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0004_auto_20190412_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Mentor', to='mentor.Mentor'),
        ),
    ]
