# Generated by Django 2.0.7 on 2019-04-13 06:19

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0006_auto_20190412_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='direccion',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Direccion'),
        ),
    ]
