# Generated by Django 2.0.7 on 2019-04-13 08:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0007_mentor_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='direccion',
        ),
        migrations.AddField(
            model_name='mentor',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Location'),
        ),
    ]
