# Generated by Django 2.0.7 on 2019-04-13 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0008_auto_20190413_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='address',
        ),
    ]
