# Generated by Django 2.0.7 on 2019-04-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0009_remove_mentor_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='DNIUpline',
            field=models.CharField(max_length=20, verbose_name='DNIUpline'),
        ),
    ]
