# Generated by Django 2.0.7 on 2019-04-25 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0003_auto_20190413_2326'),
        ('mentor', '0012_mentor_wannabementor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='entidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Mentores', to='entidad.Entidad'),
        ),
    ]
