# Generated by Django 2.0.7 on 2019-04-25 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0013_mentor_entidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='location',
        ),
    ]
