# Generated by Django 2.0.7 on 2019-04-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0014_remove_mentor_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='location'),
        ),
    ]
