# Generated by Django 2.0.7 on 2019-04-25 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0015_mentor_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ubigeos.Distrito'),
        ),
    ]
