# Generated by Django 2.0.7 on 2019-04-30 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0017_auto_20190429_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='DNI',
        ),
    ]
