# Generated by Django 2.0.7 on 2019-04-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='DNI',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='DNI'),
        ),
    ]
